name: Compile and Release Qt6 Project

on: push

env:
  QT_VERSION: "6.6.1"
  MINGW_VERSION: "win64_mingw81"
  MINGW_PATH: "mingw81_64"
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Install correct version of Mingw
      uses: crazy-max/ghaction-chocolatey@v3
      with:
        args: install mingw --version=11.0.0 -y

    - name: Install Qt
      uses: jurplel/install-qt-action@v3
      with:
        host: windows
        target: "desktop"
        version: ${{ env.QT_VERSION }}
        arch: ${{ env.MINGW_VERSION }}
        dir: "${{github.workspace}}/qt"
        install-deps: "true"

    - name: Set Qt path for qmake
      run: |
        echo "D:/a/Cryptographer/Cryptographer/qt/Qt/6.6.1/mingw81_64/bin" >> $GITHUB_PATH
        echo "D:/a/Cryptographer/Cryptographer/qt/Qt/6.6.1/mingw81_64/bin" >> $GITHUB_ENV
        echo "D:/a/Cryptographer/Cryptographer/qt/Qt/6.6.1/mingw81_64/bin" >> $env:QMAKE_PATH
      shell: powershell

    - name: Configure qmake Project
      working-directory: ${{github.workspace}}
      run: qmake -spec win32-g++ -o Makefile

    - name: Build project
      run: mingw32-make.exe

    - name: Compress portable program
      run: |
        mkdir ${{github.workspace}}\build\all\
        cp ${{github.workspace}}/build/RePr.exe ${{github.workspace}}\build\all\
        cd ${{github.workspace}}\build\all\
        windeployqt.exe RePr.exe --release
        ls
        Compress-Archive -Path ${{github.workspace}}\build\all\ -DestinationPath ${{github.workspace}}\build\final.zip

    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: windows-release
        path: ${{github.workspace}}/build/final.zip
